-- 리뷰 평균점수는 소수점 세 번째 자리에서 반올림
--  결과는 평균점수를 기준으로 내림차순 정렬, 즐겨찾기 수 내림차순

SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS I JOIN REST_REVIEW AS R ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE "서울%"
GROUP BY I.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC